<a href="https://colab.research.google.com/github/kaykizzzle/iGEM.learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


#resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


tensors are a way to represent multidimensional data (scalar, vector, matrix, etc.)


In [4]:
scalar = torch.tensor(7)
scalar.ndim
scalar.item()

vector = torch.tensor([7,7])
vector.ndim  #number of dimensions is number of square brackets
vector.shape #number of elements

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX.ndim
MATRIX.shape
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX[:,0])

tensor([7, 8])
tensor([ 9, 10])
tensor([7, 9])


In [5]:
TENSOR = torch.tensor([[[1,2,3],
                    [3,6,9],
                    [2,4,5]]])
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


###random tensors

random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [6]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3963, 0.5586, 0.4683, 0.2260],
        [0.8205, 0.8649, 0.0508, 0.4293],
        [0.1690, 0.3753, 0.2697, 0.9708]])

In [7]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim
#sometimes color channels can go first, sometimes last!

(torch.Size([224, 224, 3]), 3)

### Zeros and ones


In [11]:
#create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
print(zeros, zeros.dtype)
print(zeros*random_tensor)

#create a tensor of all ones
ones = torch.ones(size=(3,4))
print(ones, ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) torch.float32
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) torch.float32


###Creating a range of tensors and tensors-like

In [18]:
one_to_ten = torch.arange(start=0,end=1000, step=77)
one_to_ten
ten_zeros = torch.zeros_like(input=one_to_ten)
print(ten_zeros)
# zeros in the same shape as one_to_ten

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [22]:
float32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, device=None, requires_grad=False)
print(float32_tensor)
#dtype is what datatype the tensor is (most common is 16b and 32b), deal with precision and computing
#device can be cuda or cpu (need to be the same for all compatible tensors)
#requires_grad true or false, do we want pytorch to track the gradients as the tensor undergoes calculations?
float_16_tensor = float32_tensor.type(torch.float16)
print(float_16_tensor) #switch from 32b data type to 16b data type

#you can perform some operations where the data types are different but some
# data types aren't compatible for certain operations!

tensor([3., 6., 9.])
tensor([3., 6., 9.], dtype=torch.float16)


###Manipulating tensors

Include...


*   addition
*   subtraction


*   multiplication/division
*   matrix multiplication (dot product)





In [24]:
tensor = torch.tensor([1,2,3])
print(tensor + 10,
tensor - 10,
tensor * 10,
tensor / 10)

tensor([11, 12, 13]) tensor([-9, -8, -7]) tensor([10, 20, 30]) tensor([0.1000, 0.2000, 0.3000])


In [27]:
print(tensor)
#element wise multiplication
print(tensor * tensor)
#matrix multiplication
print(torch.matmul(tensor,tensor))

tensor([1, 2, 3])
tensor([1, 4, 9])
tensor(14)


###shape errors...
one of the most common errors in matrix multiplications
1. the inner dimensions must match (3,2) @ (2,3) will work but (3,2) @ (3,2) WONT work
2. resulting matrix has the shape of the outer dimensions

In [ ]:
#transposing the matrix fixes shape issues

In [34]:
tensor1 = torch.rand(3,2)
tensor2 = torch.rand(3,2)
tensor3 = tensor2.T #flips dimensions
print(torch.mm(tensor1, tensor3))

tensor([[0.2854, 0.3275, 0.5589],
        [0.4924, 0.7263, 0.3597],
        [0.2754, 0.3830, 0.2879]])


###Tensor Aggregation

In [38]:
x = torch.arange(0,100,10)
print(x,
x.min(),
x.max(),
torch.mean(x.type(torch.float32)),
x.sum())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) tensor(0) tensor(90) tensor(45.) tensor(450)


###Find positional min and max

In [ ]:
print(x)
print(x.argmin())
#returns index position of target tensor where minimum value occurs, argmax does the same with the max value
print(x.argmax())

###Reshaping, stacking, squeezing, and unsqueezing

- reshaping = reshapes an input tesnor to a defined shape
- view = return a view of an input tensor of certain shape but keep the same memory as the original tensor
- stacking = combine multiple tesnors ontop or side by side (vstack or hstack)
- squeeze = remove all '1' dimensions from a tensor
- unsqueeze = add a '1' dimension to a target tensor
- permute = return a view of the input with dimensions permuted (swapped) in a certain way

In [69]:
#reshape
y = torch.arange(1,11) #only from 1 to 10
print(y)
print(y.shape)
print(y.reshape(5,2), y.reshape(2,5), y.reshape(1,10))
#want the reshape to multiply to equal the shape

#change the view
z = y.view(1,10)
print(z) #changing z changes y because a view of tensor shares the same memory as the original

#stack tensors on top of each other
y_stacked = torch.stack([y,y,y,y], dim=0)
print(y_stacked)

#squeeze tensors, fix dimension mismatch!
y_reshaped = y.reshape(1,10)
y_squeezed = y_reshaped.squeeze()
print(y_reshaped.shape, y_squeezed.shape)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
torch.Size([10])
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]) tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]) tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
torch.Size([1, 10]) torch.Size([10])
