<a href="https://colab.research.google.com/github/kaykizzzle/iGEM.learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


#resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


tensors are a way to represent multidimensional data (scalar, vector, matrix, etc.)


In [10]:
scalar = torch.tensor(7)
scalar.ndim
scalar.item()

vector = torch.tensor([7,7])
vector.ndim  #number of dimensions is number of square brackets
vector.shape #number of elements

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX.ndim
MATRIX.shape
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX[:,0])


tensor([7, 8])
tensor([ 9, 10])
tensor([7, 9])
