<a href="https://colab.research.google.com/github/kaykizzzle/iGEM.learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!nvidia-smi


Thu Jun 27 17:38:51 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

#resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


tensors are a way to represent multidimensional data (scalar, vector, matrix, etc.)


In [5]:
scalar = torch.tensor(7)
scalar.ndim
scalar.item()

vector = torch.tensor([7,7])
vector.ndim  #number of dimensions is number of square brackets
vector.shape #number of elements

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX.ndim
MATRIX.shape
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX[:,0])

tensor([7, 8])
tensor([ 9, 10])
tensor([7, 9])


In [6]:
TENSOR = torch.tensor([[[1,2,3],
                    [3,6,9],
                    [2,4,5]]])
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


###random tensors

random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [7]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4085, 0.2307, 0.1021, 0.4075],
        [0.8055, 0.7363, 0.0658, 0.7924],
        [0.2974, 0.8021, 0.2793, 0.7887]])

In [8]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim
#sometimes color channels can go first, sometimes last!

(torch.Size([224, 224, 3]), 3)

### Zeros and ones


In [9]:
#create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
print(zeros, zeros.dtype)
print(zeros*random_tensor)

#create a tensor of all ones
ones = torch.ones(size=(3,4))
print(ones, ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) torch.float32
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) torch.float32


###Creating a range of tensors and tensors-like

In [10]:
one_to_ten = torch.arange(start=0,end=1000, step=77)
one_to_ten
ten_zeros = torch.zeros_like(input=one_to_ten)
print(ten_zeros)
# zeros in the same shape as one_to_ten

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [11]:
float32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, device=None, requires_grad=False)
print(float32_tensor)
#dtype is what datatype the tensor is (most common is 16b and 32b), deal with precision and computing
#device can be cuda or cpu (need to be the same for all compatible tensors)
#requires_grad true or false, do we want pytorch to track the gradients as the tensor undergoes calculations?
float_16_tensor = float32_tensor.type(torch.float16)
print(float_16_tensor) #switch from 32b data type to 16b data type

#you can perform some operations where the data types are different but some
# data types aren't compatible for certain operations!

tensor([3., 6., 9.])
tensor([3., 6., 9.], dtype=torch.float16)


###Manipulating tensors

Include...


*   addition
*   subtraction


*   multiplication/division
*   matrix multiplication (dot product)





In [12]:
tensor = torch.tensor([1,2,3])
print(tensor + 10,
tensor - 10,
tensor * 10,
tensor / 10)

tensor([11, 12, 13]) tensor([-9, -8, -7]) tensor([10, 20, 30]) tensor([0.1000, 0.2000, 0.3000])


In [13]:
print(tensor)
#element wise multiplication
print(tensor * tensor)
#matrix multiplication
print(torch.matmul(tensor,tensor))

tensor([1, 2, 3])
tensor([1, 4, 9])
tensor(14)


###shape errors...
one of the most common errors in matrix multiplications
1. the inner dimensions must match (3,2) @ (2,3) will work but (3,2) @ (3,2) WONT work
2. resulting matrix has the shape of the outer dimensions

In [14]:
#transposing the matrix fixes shape issues

In [15]:
tensor1 = torch.rand(3,2)
tensor2 = torch.rand(3,2)
tensor3 = tensor2.T #flips dimensions
print(torch.mm(tensor1, tensor3))

tensor([[0.4003, 0.3175, 0.4612],
        [0.1168, 0.1639, 0.1925],
        [0.5146, 0.4981, 0.6661]])


###Tensor Aggregation

In [16]:
x = torch.arange(0,100,10)
print(x,
x.min(),
x.max(),
torch.mean(x.type(torch.float32)),
x.sum())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) tensor(0) tensor(90) tensor(45.) tensor(450)


###Find positional min and max

In [17]:
print(x)
print(x.argmin())
#returns index position of target tensor where minimum value occurs, argmax does the same with the max value
print(x.argmax())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0)
tensor(9)


###Reshaping, stacking, squeezing, and unsqueezing

- reshaping = reshapes an input tesnor to a defined shape
- view = return a view of an input tensor of certain shape but keep the same memory as the original tensor
- stacking = combine multiple tesnors ontop or side by side (vstack or hstack)
- squeeze = remove all '1' dimensions from a tensor
- unsqueeze = add a '1' dimension to a target tensor
- permute = return a view of the input with dimensions permuted (swapped) in a certain way

In [18]:
#reshape
y = torch.arange(1,11) #only from 1 to 10
print(y)
print(y.shape)
print(y.reshape(5,2), y.reshape(2,5), y.reshape(1,10))
#want the reshape to multiply to equal the shape

#change the view
z = y.view(1,10)
print(z) #changing z changes y because a view of tensor shares the same memory as the original

#stack tensors on top of each other
y_stacked = torch.stack([y,y,y,y], dim=0)
print(y_stacked)

#squeeze tensors, fix dimension mismatch!
y_reshaped = y.reshape(1,10)
y_squeezed = y_reshaped.squeeze()
print(y_reshaped.shape, y_squeezed.shape)

#unsqueeze tensors, fix dimension mismatch!
# adds a single dimension to a target tensor at a specific dimension
y_unsqueezed = y_squeezed.unsqueeze(dim=1)
print(y_unsqueezed.shape)

#permute rearranges the dimensions in a certain order
x_original = torch.rand(size=(224,224,3)) #height, width, color channels
print(x_original.size())
x_permuted = x_original.permute(2,0,1) #second dimension is first, 0th dimension is second, first dimension is third
print(x_permuted.size()) #color channels, height, width

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
torch.Size([10])
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]) tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]) tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
torch.Size([1, 10]) torch.Size([10])
torch.Size([10, 1])
torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


###Indexing (selecting data from tensors)

In [19]:
x = torch.arange(1,10).reshape(1,3,3)
print(x, x.shape)
print(x[0])
print(x[0][0])
print(x[0][0][0])
print(x[0][2][2])

#get all in the 0th dimension and only index 0 of the first dimenstion
print(x[:,0])
#get all in the 0th and 1st dimensions and only index 1 of the 2nd dimension
print(x[:,:,1])
#get only 9
print(x[:,2,2])
#get 3,6,9
print(x[:,:,2])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)
tensor(9)
tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([9])
tensor([[3, 6, 9]])


###Pytorch tensors and numpy
numpy is a popular scientific python numerical computing library
because of this, pytorch has functionality to interact with it
- data in numpy, want in pytorch tensor -> torch.from_numpy(ndarray)
-pytorch tensor -> numpy -> torch.Tensor.numpy()

In [20]:
#numpy array to tensor
import numpy as np
import torch

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
print(array, tensor)
#numpys default datatype is float64
#

[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


###Putting tensors and models on the GPU

Using a GPU results in faster calculations

In [24]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

#create "device" parameter (moves to GPU if possible, keeps on CPU if necessary)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

#move to the GPU/target device
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

#move tensor back to CPU (can't transform tensor to numpy when on GPU)
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_back_on_cpu)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0
[1 2 3]


###PyTorch workflow

1. get data ready (turn into tensors)
2. build or pick a pretrained model (to suit your problem), pick a loss function and optimizer, build a training loop
3. fit the model to the data and make a prediction
4. evaluate the model
5. improve through experimentation
6. save and reload your trained model

